# Generated by Django 5.1.2 on 2024-10-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NETFLIX', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='name',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.AddField(
            model_name='description',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='NETFLIX.subscriptionplan'),
        ),
    ]
