# Generated by Django 5.1.2 on 2024-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NETFLIX', '0003_subscriptionplan_interval_subscriptionplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_id',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
